### ISSUE TITLE
Support for FreeBSD / FreeNAS ?

### ISSUE THREAD

**Issue by 3isenHeiM** [earthquake/XFLTReaT#4]
Hi, awesome project, I've seen tour talk @BruCON last year about it !

I'm trying to install it on my NAS which runs FreeNAS (FreeBSD-based), that I can access from whereever I want...
When I run the server, I get this error : 
``[-] Sorry buddy, I am afraid that your OS is not yet supported``

Is it not supported, or is there a simple manipulation to make it work ?

Thanks !

**Comment by 3isenHeiM** [comment]
I've checked by modifying the ``common.py`` on line 57 by adding ``| OS_FREEBSD``.

If I try to run the server I get this : 

    freenas# sudo python2.7 xfltreat.py
    [..banner..]
    [-] The tool needs superuser or admin privileges. Run as root or Administrator.
    freenas# whoami
    root

Any ideas ?

**Comment by 3isenHeiM** [comment]
I modified also, in my clone, the line 156 of ``common.py`` when checking the superuser rights on the OS.
    	`if (os_type == OS_LINUX) or (os_type == OS_MACOSX) or (os_type == OS_FREEBSD):`

I think it should also be done for other *NIX OSes ;)

**Comment by earthquake** [comment]
This is on the roadmap. It should not be that hard to support FreeBSD. You are on the right track, please create a pull request with your modifications whenever you feel ready or partly ready.
I imaging the hardest part is to set up the interface (ioctls) and the routing, but that is fairly similar to the Linux one.

**Comment by 3isenHeiM** [comment]
Indeed, I'm currently fiddling with ioctls :)

**Comment by earthquake** [comment]
Can you make a pull request with your stuff that you have so far? I might have some time today to help you on this. But not totally sure, so keep up the good work even after that!

**Comment by earthquake** [comment]
@3isenHeiM: the next-version branch should have a working FreeBSD implementation now. Can you test it please?

**Comment by 3isenHeiM** [comment]
Yeah totally ! I'll run it on my FreeNas and give feedback ;)

**Comment by earthquake** [comment]
any news? @3isenHeiM ?

**Comment by earthquake** [comment]
FreeBSD support added a while ago. This is closed now.
