### ISSUE TITLE
windows 10 tun device problem

### ISSUE THREAD

**Issue by demianrey** [earthquake/XFLTReaT#8]
hello, first of all congratulate you for a great job, now the query: I install the openvpn tun/tap drivers for windows 10, and the following appears:

[39m[*] Parsing config file[39m
[39m[*] Loading all modules from 'modules' directory[39m
[39m[*] Setting up interface[39m
Traceback (most recent call last):
  File "xfltreat.py", line 399, in <module>
    xfltreat.run(sys.argv[1:])
  File "xfltreat.py", line 274, in run
    client_tunnel = interface.tun_alloc(config.get("Global", "clientif"), interface.IFF_TUN|interface.IFF_NO_PI)
  File "C:\Users\demia\OneDrive\Escritorio\DNS\XFLTReaT\interface.py", line 682, in win_tun_alloc
    win32file.DeviceIoControl(self.wintun, TAP_IOCTL_SET_MEDIA_STATUS, '\x01\x00\x00\x00', 1, None)
TypeError: a bytes-like object is required, not 'str'

any suggestions?
regards

**Comment by earthquake** [comment]
Thank you!
Next time please give more details on your setup. I guess this is Python3 and the next-version branch.
For some reason the last bunch of commits were not pushed up to github so it was missing a few bits.
Please refresh your local copy by pulling the latest next-version. Hopefully it will work now, although I had some issues with the RDP module.

**Comment by earthquake** [comment]
no reply, assumed to be solved.
